apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../deployment/k8s/namespace.yaml
  - ../../deployment/k8s/api-deployment.yaml
  - ../../deployment/k8s/agent-registry.yaml
  - ../../deployment/k8s/go-scanner.yaml
  - ../../deployment/k8s/rust-labyrinth.yaml
  - ../../deployment/k8s/anchor-service.yaml
  - ../../deployment/k8s/vault-ha.yaml
  - ../../deployment/k8s/hpa-api.yaml
  - ../../deployment/k8s/pdb-api.yaml
