global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka1:9092', 'kafka2:9093', 'kafka3:9094']
    scrape_interval: 15s

  - job_name: 'ingest-workers'
    static_configs:
      - targets: ['ingest-worker:8000']
    scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093