apiVersion: v1
kind: Namespace
metadata:
  name: infinite-ai
  labels:
    name: infinite-ai
    security.policy: strict
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-system
  labels:
    name: vault-system
    security.policy: maximum